apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/shayFoo/dispatcher-service/k8s?ref=master
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: dispatcher-config
images:
- name: dispatcher-service
  newName: ghcr.io/shayfoo/dispatcher-service
  newTag: latest
replicas:
- count: 2
  name: dispatcher-service
