apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/shayFoo/edge-service/k8s?ref=master
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: edge-config
images:
- name: edge-service
  newName: ghcr.io/shayfoo/edge-service
  newTag: latest
replicas:
- count: 2
  name: edge-service
