apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resource-secret-volume
              mountPath: /workspace/secrets/keycloak
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: polar-postgres-order-credentials
        - name: keycloak-issuer-resource-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret
        - name: rabbitmq-credentials-volume
          secret:
            secretName: polar-rabbitmq-credentials