apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/shayFoo/edge-service/k8s?ref=master
configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config
patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml
- path: patch-ingress.yml
images:
- name: edge-service
  newName: ghcr.io/shayfoo/edge-service
  newTag: 55d45ff8ae04daea69db5cf683e7d2070caa87fc
replicas:
- count: 2
  name: edge-service
