apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/shayFoo/order-service/k8s?ref=main
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: order-config
images:
- name: order-service
  newName: ghcr.io/shayfoo/order-service
  newTag: latest
replicas:
- count: 2
  name: order-service
